### ISSUE TITLE
docker deployment Cannot resolve dependency 'prism-react-renderer'

### ISSUE THREAD

**Issue by longilineo** [remoteinterview/zero#104]
My app consist of a jsx page that consumes some api (in js files). When I build this app locally everything works, but fails when I try to follow the example [running with docker ](https://zeroserver.io/docs/deploying#running-with-docker)

The error is the following:

>🚨  /app/.zero/mdx.5605281e115bf9992afe2198de36c8caaecdaac5.js:2:38: Cannot resolve dependency 'prism-react-renderer'
  1 | 
 2 | import Highlight, {defaultProps} from 'prism-react-renderer'
    |                                      ^
  3 | import {mdx} from '@mdx-js/react'
  4 | import {MDXProvider} from '@mdx-js/react'
  5 | var AppAndExports = require('../app/index.jsx')
(node:96) UnhandledPromiseRejectionWarning: Error: Cannot resolve dependency 'prism-react-renderer'
    at Resolver.resolve (/usr/local/lib/node_modules/zero/node_modules/parcel-bundler/src/Resolver.js:71:17)
    at async Bundler.resolveAsset (/usr/local/lib/node_modules/zero/node_modules/parcel-bundler/src/Bundler.js:433:18)
    at async Bundler.resolveDep (/usr/local/lib/node_modules/zero/node_modules/parcel-bundler/src/Bundler.js:484:14)
    at async /usr/local/lib/node_modules/zero/node_modules/parcel-bundler/src/Bundler.js:608:26
    at async Promise.all (index 4)
    at async Bundler.loadAsset (/usr/local/lib/node_modules/zero/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async Bundler.processAsset (/usr/local/lib/node_modules/zero/node_modules/parcel-bundler/src/Bundler.js:557:5)
    at async PromiseQueue._runJob (/usr/local/lib/node_modules/zero/node_modules/parcel-bundler/src/utils/PromiseQueue.js:48:7)
(node:96) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by asadm** [comment]
It looks like a bug in current release (1.1.17). I have pushed a patch. Can you try to build again with v1.1.18.
