### ISSUE TITLE
Parcel plugins does not works.

### ISSUE THREAD

**Issue by vytenis-nfq** [remoteinterview/zero#42]
Check `components/counter/simple-counter.js` file. It should output to console the css object. Works with `parcel` and does not works with `zero`

```Zero v1.0.12-alpha.3```
[zero-bug.zip](https://github.com/remoteinterview/zero/files/2956645/zero-bug.zip)

**Comment by vytenis-nfq** [comment]
Also probably other bug is I cant build the project
```$ npm run zero -- build --no-source-maps```
Got error:
```
✷ Updating packagesnpm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 374 packages from 213 contributors and audited 3231 packages in 9.032s
found 0 vulnerabilities

(node:16293) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/tmp/zeroservertmp/652ee2a810b83c797f3395b256153e327c1beb3e/zero-builds/build-info.json'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at build (/home/***/zero/node_modules/zero/lib/index.js:137:12)
(node:16293) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16293) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I tried clearing the tmp directory same result.

**Comment by vytenis-nfq** [comment]
```$ npm run zero -- build```
Got error and stuck:
```
> zero "build"

✺ Updating packages(node:16643) UnhandledPromiseRejectionWarning: Error: Invalid package name "_css_loader": name cannot start with an underscore
    at invalidPackageName (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:82:15)
    at Result.setName (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:118:11)
    at new Result (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:107:23)
    at Function.resolve (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:54:15)
    at Object.keys.map (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/lib/install/deps.js:466:20)
    at Array.map (<anonymous>)
    at BB.resolve.then (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/lib/install/deps.js:465:47)
    at tryCatcher (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/***/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
(node:16643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16643) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✹ Updating packages
```
