### ISSUE TITLE
Zero does not work on my vps server.

### ISSUE THREAD

**Issue by jywhy6** [remoteinterview/zero#43]
VPS information: DigitalOcean, CentOS

Error log:
/usr/lib/node_modules/zero/lib/index.js:85
  return new Promise(async (resolve, reject) => {
                           ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/zero/bin/zero:2:36)

**Comment by asadm** [comment]
Can you tell me the node version?

**Comment by jywhy6** [comment]
> Can you tell me the node version?

6.16.0

**Comment by jywhy6** [comment]
> Can you tell me the node version?

Thank you for your help, I upgraded my node version and now Zero works.
