### ISSUE TITLE
Deploying Under CapRover

### ISSUE THREAD

**Issue by WriteCodeEveryday** [remoteinterview/zero#95]
Trying to deploy under CapRover using the following configuration.

captain-definition File
`{
  "schemaVersion": 2,
  "templateId": "node/12.1.0"
 }`

package.json
`"scripts": {
    "start": "node_modules/db-migrate/bin/db-migrate up && node_modules/zero/bin/zero"
},`

Output
`2019-11-11T02:32:17.345928397Z > app@1.0.0 start /usr/src/app
2019-11-11T02:32:17.345934867Z > node_modules/db-migrate/bin/db-migrate up && node_modules/zero/bin/zero
2019-11-11T02:32:17.345939097Z
2019-11-11T02:32:18.071891438Z [INFO] Processed migration 20191012211546-add-pending-charge
2019-11-11T02:32:18.089618863Z [INFO] Processed migration 20191012214856-add-pending-shipping
2019-11-11T02:32:18.105999664Z [INFO] Done
2019-11-11T02:32:19.253662332Z ⚡️ Zero v1.1.4
2019-11-11T02:32:34.203948565Z ⬇️ Updating packages
2019-11-11T02:32:36.191417382Z yarn install v1.19.1
2019-11-11T02:32:36.213498231Z warning package.json: No license field
2019-11-11T02:32:36.401447943Z warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
2019-11-11T02:32:36.403488469Z warning app@1.0.0: No license field
2019-11-11T02:32:36.406843010Z [1/4] Resolving packages...
2019-11-11T02:32:40.890510458Z [2/4] Fetching packages...
2019-11-11T02:33:21.318758554Z info fsevents@1.2.9: The platform "linux" is incompatible with this module.
2019-11-11T02:33:21.319369776Z info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
2019-11-11T02:33:21.327757182Z info fsevents@2.0.7: The platform "linux" is incompatible with this module.
2019-11-11T02:33:21.328002962Z info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
2019-11-11T02:33:21.343966032Z [3/4] Linking dependencies...
2019-11-11T02:33:21.349772350Z warning " > pdfjs-dist@2.2.228" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
2019-11-11T02:33:21.350089981Z warning "pdfjs-dist > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
2019-11-11T02:33:21.351760156Z warning "react-pdf > pdfjs-dist@2.1.266" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
2019-11-11T02:33:21.359346119Z warning "zero > zero-builders-map > zero-builder-react > @mdx-js/parcel-plugin-mdx@0.17.5" has unmet peer dependency "@mdx-js/tag@^0.13.1-1".
2019-11-11T02:33:39.095807601Z [4/4] Building fresh packages...
2019-11-11T02:33:40.687904030Z success Saved lockfile.
2019-11-11T02:33:40.693444517Z Done in 64.51s.
2019-11-11T02:33:40.735416116Z - Generating manifest
2019-11-11T02:33:58.037648023Z ✔ Server running on http://localhost:80
2019-11-11T02:36:45.872201111Z - Building /
2019-11-11T02:36:49.487265022Z /bin/sh: lscpu: not found
2019-11-11T02:36:49.887459743Z /bin/sh: lscpu: not found
2019-11-11T02:37:59.041871375Z - Serving /
2019-11-11T02:37:59.254193288Z Error: Cannot find module '/usr/src/app/.zero/node_modules/react'
2019-11-11T02:37:59.254253639Z Require stack:
2019-11-11T02:37:59.254258679Z - /usr/src/app/node_modules/zero-handler-react/renderer/index.js
2019-11-11T02:37:59.254262879Z - /usr/src/app/node_modules/zero-handler-react/process.js
2019-11-11T02:37:59.254267009Z - /usr/src/app/node_modules/zero-handlers-map/index.js
2019-11-11T02:37:59.254270709Z - /usr/src/app/node_modules/zero/lib/builder/buildManifest.js
2019-11-11T02:37:59.254274079Z - /usr/src/app/node_modules/zero/lib/builder/index.js
2019-11-11T02:37:59.254277609Z - /usr/src/app/node_modules/zero/lib/index.js
2019-11-11T02:37:59.254329048Z - /usr/src/app/node_modules/zero/bin/zero
2019-11-11T02:37:59.254332838Z at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
2019-11-11T02:37:59.254336138Z at Function.Module._load (internal/modules/cjs/loader.js:526:27)
2019-11-11T02:37:59.254339468Z at Module.require (internal/modules/cjs/loader.js:666:19)
2019-11-11T02:37:59.254342788Z at require (internal/modules/cjs/helpers.js:16:16)
2019-11-11T02:37:59.254346158Z at localRequire (/usr/src/app/node_modules/zero-handler-react/renderer/index.js:2:10)
2019-11-11T02:37:59.254349588Z at Object.<anonymous> (/usr/src/app/node_modules/zero-handler-react/renderer/index.js:13:15)
2019-11-11T02:37:59.254353708Z at Module._compile (internal/modules/cjs/loader.js:759:30)
2019-11-11T02:37:59.254357058Z at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
2019-11-11T02:37:59.254360438Z at Module.load (internal/modules/cjs/loader.js:628:32)
2019-11-11T02:37:59.254363708Z at Function.Module._load (internal/modules/cjs/loader.js:555:12) {
2019-11-11T02:37:59.254367168Z code: 'MODULE_NOT_FOUND',
2019-11-11T02:37:59.254370308Z requireStack: [
2019-11-11T02:37:59.254373348Z '/usr/src/app/node_modules/zero-handler-react/renderer/index.js',
2019-11-11T02:37:59.254376518Z '/usr/src/app/node_modules/zero-handler-react/process.js',
2019-11-11T02:37:59.254379978Z '/usr/src/app/node_modules/zero-handlers-map/index.js',
2019-11-11T02:37:59.254383178Z '/usr/src/app/node_modules/zero/lib/builder/buildManifest.js',
2019-11-11T02:37:59.254386448Z '/usr/src/app/node_modules/zero/lib/builder/index.js',
2019-11-11T02:37:59.254389618Z '/usr/src/app/node_modules/zero/lib/index.js',
2019-11-11T02:37:59.254406828Z '/usr/src/app/node_modules/zero/bin/zero'
2019-11-11T02:37:59.254410488Z ]
2019-11-11T02:37:59.254413678Z }
2019-11-11T12:39:01.287927369Z Error: Cannot find module '/usr/src/app/.zero/node_modules/react'
2019-11-11T12:39:01.288000490Z Require stack:
2019-11-11T12:39:01.288017720Z - /usr/src/app/node_modules/zero-handler-react/renderer/index.js
2019-11-11T12:39:01.288021710Z - /usr/src/app/node_modules/zero-handler-react/process.js
2019-11-11T12:39:01.288025140Z - /usr/src/app/node_modules/zero-handlers-map/index.js
2019-11-11T12:39:01.288028360Z - /usr/src/app/node_modules/zero/lib/builder/buildManifest.js
2019-11-11T12:39:01.288031450Z - /usr/src/app/node_modules/zero/lib/builder/index.js
2019-11-11T12:39:01.288034680Z - /usr/src/app/node_modules/zero/lib/index.js
2019-11-11T12:39:01.288037660Z - /usr/src/app/node_modules/zero/bin/zero
2019-11-11T12:39:01.288040690Z at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
2019-11-11T12:39:01.288043800Z at Function.Module._load (internal/modules/cjs/loader.js:526:27)
2019-11-11T12:39:01.288046930Z at Module.require (internal/modules/cjs/loader.js:666:19)
2019-11-11T12:39:01.288065120Z at require (internal/modules/cjs/helpers.js:16:16)
2019-11-11T12:39:01.288068340Z at localRequire (/usr/src/app/node_modules/zero-handler-react/renderer/index.js:2:10)
2019-11-11T12:39:01.288071490Z at Object.<anonymous> (/usr/src/app/node_modules/zero-handler-react/renderer/index.js:13:15)
2019-11-11T12:39:01.288075470Z at Module._compile (internal/modules/cjs/loader.js:759:30)
2019-11-11T12:39:01.288082820Z at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
2019-11-11T12:39:01.288085850Z at Module.load (internal/modules/cjs/loader.js:628:32)
2019-11-11T12:39:01.288088990Z at Function.Module._load (internal/modules/cjs/loader.js:555:12) {
2019-11-11T12:39:01.288092000Z code: 'MODULE_NOT_FOUND',
2019-11-11T12:39:01.288094960Z requireStack: [
2019-11-11T12:39:01.288097910Z '/usr/src/app/node_modules/zero-handler-react/renderer/index.js',
2019-11-11T12:39:01.288100950Z '/usr/src/app/node_modules/zero-handler-react/process.js',
2019-11-11T12:39:01.288103910Z '/usr/src/app/node_modules/zero-handlers-map/index.js',
2019-11-11T12:39:01.288106930Z '/usr/src/app/node_modules/zero/lib/builder/buildManifest.js',
2019-11-11T12:39:01.288109950Z '/usr/src/app/node_modules/zero/lib/builder/index.js',
2019-11-11T12:39:01.288113000Z '/usr/src/app/node_modules/zero/lib/index.js',
2019-11-11T12:39:01.288116130Z '/usr/src/app/node_modules/zero/bin/zero'
2019-11-11T12:39:01.288119140Z ]
2019-11-11T12:39:01.288122060Z }`

Should I add react as an implicit dependency?

**Comment by asadm** [comment]
By any chance, do you have `.zero/` directory checked into your source code? Try deleting it and then deploying?

**Comment by WriteCodeEveryday** [comment]
Checked the local git repo, there's no .zero folder in Bitbucket or locally.

I'm using a local install of zero instead of a global install, do you think that could be the problem?

**Comment by asadm** [comment]
Can you try with the latest version. I did a fix for this kind of error.

**Comment by WriteCodeEveryday** [comment]
No luck, issue persists.

`2019-11-24T03:28:07.750933775Z - Building /
2019-11-24T03:28:13.568483305Z /bin/sh: lscpu: not found
2019-11-24T03:28:14.152028702Z /bin/sh: lscpu: not found
2019-11-24T03:28:25.115843523Z - Serving /
2019-11-24T03:28:25.755812771Z Error: Cannot find module '/usr/src/app/.zero/node_modules/react'
2019-11-24T03:28:25.755867901Z Require stack:
2019-11-24T03:28:25.755896731Z - /usr/src/app/node_modules/zero-handler-react/renderer/index.js
2019-11-24T03:28:25.755901081Z - /usr/src/app/node_modules/zero-handler-react/process.js
2019-11-24T03:28:25.755904681Z - /usr/src/app/node_modules/zero-handlers-map/index.js
2019-11-24T03:28:25.755908041Z - /usr/src/app/node_modules/zero/lib/builder/buildManifest.js
2019-11-24T03:28:25.755911341Z - /usr/src/app/node_modules/zero/lib/builder/index.js
2019-11-24T03:28:25.755914571Z - /usr/src/app/node_modules/zero/lib/index.js
2019-11-24T03:28:25.755917691Z - /usr/src/app/node_modules/zero/bin/zero
2019-11-24T03:28:25.755921121Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
2019-11-24T03:28:25.755924311Z     at Function.Module._load (internal/modules/cjs/loader.js:526:27)
2019-11-24T03:28:25.755927461Z     at Module.require (internal/modules/cjs/loader.js:666:19)
2019-11-24T03:28:25.755930631Z     at require (internal/modules/cjs/helpers.js:16:16)
2019-11-24T03:28:25.755933791Z     at localRequire (/usr/src/app/node_modules/zero-handler-react/renderer/index.js:2:10)
2019-11-24T03:28:25.755937051Z     at Object.<anonymous> (/usr/src/app/node_modules/zero-handler-react/renderer/index.js:13:15)
2019-11-24T03:28:25.755941171Z     at Module._compile (internal/modules/cjs/loader.js:759:30)
2019-11-24T03:28:25.755944411Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
2019-11-24T03:28:25.755947621Z     at Module.load (internal/modules/cjs/loader.js:628:32)
2019-11-24T03:28:25.755950761Z     at Function.Module._load (internal/modules/cjs/loader.js:555:12) {
2019-11-24T03:28:25.755953991Z   code: 'MODULE_NOT_FOUND',
2019-11-24T03:28:25.755957061Z   requireStack: [
2019-11-24T03:28:25.755974031Z     '/usr/src/app/node_modules/zero-handler-react/renderer/index.js',
2019-11-24T03:28:25.755977271Z     '/usr/src/app/node_modules/zero-handler-react/process.js',
2019-11-24T03:28:25.755980431Z     '/usr/src/app/node_modules/zero-handlers-map/index.js',
2019-11-24T03:28:25.755983571Z     '/usr/src/app/node_modules/zero/lib/builder/buildManifest.js',
2019-11-24T03:28:25.755986701Z     '/usr/src/app/node_modules/zero/lib/builder/index.js',
2019-11-24T03:28:25.755989821Z     '/usr/src/app/node_modules/zero/lib/index.js',
2019-11-24T03:28:25.755992961Z     '/usr/src/app/node_modules/zero/bin/zero'
2019-11-24T03:28:25.756010291Z   ]
2019-11-24T03:28:25.756013881Z }
2019-11-24T03:28:38.484438435Z - Serving /
2019-11-24T03:28:38.490539469Z Error: Cannot find module '/usr/src/app/.zero/node_modules/react'
2019-11-24T03:28:38.490593508Z Require stack:
2019-11-24T03:28:38.490598088Z - /usr/src/app/node_modules/zero-handler-react/renderer/index.js
2019-11-24T03:28:38.490601808Z - /usr/src/app/node_modules/zero-handler-react/process.js
2019-11-24T03:28:38.490605318Z - /usr/src/app/node_modules/zero-handlers-map/index.js
2019-11-24T03:28:38.490608998Z - /usr/src/app/node_modules/zero/lib/builder/buildManifest.js
2019-11-24T03:28:38.490612278Z - /usr/src/app/node_modules/zero/lib/builder/index.js
2019-11-24T03:28:38.490615408Z - /usr/src/app/node_modules/zero/lib/index.js
2019-11-24T03:28:38.490618508Z - /usr/src/app/node_modules/zero/bin/zero
2019-11-24T03:28:38.490621618Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
2019-11-24T03:28:38.490624798Z     at Function.Module._load (internal/modules/cjs/loader.js:526:27)
2019-11-24T03:28:38.490627918Z     at Module.require (internal/modules/cjs/loader.js:666:19)
2019-11-24T03:28:38.490631058Z     at require (internal/modules/cjs/helpers.js:16:16)
2019-11-24T03:28:38.490634168Z     at localRequire (/usr/src/app/node_modules/zero-handler-react/renderer/index.js:2:10)
2019-11-24T03:28:38.490637398Z     at Object.<anonymous> (/usr/src/app/node_modules/zero-handler-react/renderer/index.js:13:15)
2019-11-24T03:28:38.490641458Z     at Module._compile (internal/modules/cjs/loader.js:759:30)
2019-11-24T03:28:38.490645328Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
2019-11-24T03:28:38.490648598Z     at Module.load (internal/modules/cjs/loader.js:628:32)
2019-11-24T03:28:38.490651988Z     at Function.Module._load (internal/modules/cjs/loader.js:555:12) {
2019-11-24T03:28:38.490655118Z   code: 'MODULE_NOT_FOUND',
2019-11-24T03:28:38.490658148Z   requireStack: [
2019-11-24T03:28:38.490661168Z     '/usr/src/app/node_modules/zero-handler-react/renderer/index.js',
2019-11-24T03:28:38.490664368Z     '/usr/src/app/node_modules/zero-handler-react/process.js',
2019-11-24T03:28:38.490667488Z     '/usr/src/app/node_modules/zero-handlers-map/index.js',
2019-11-24T03:28:38.490670648Z     '/usr/src/app/node_modules/zero/lib/builder/buildManifest.js',
2019-11-24T03:28:38.490673778Z     '/usr/src/app/node_modules/zero/lib/builder/index.js',
2019-11-24T03:28:38.490676898Z     '/usr/src/app/node_modules/zero/lib/index.js',
2019-11-24T03:28:38.490680028Z     '/usr/src/app/node_modules/zero/bin/zero'
2019-11-24T03:28:38.490683148Z   ]
2019-11-24T03:28:38.490686128Z }`

Could it have something to do with the lscpu error?

**Comment by WriteCodeEveryday** [comment]
CapRover was installing version 1.1.4. Manually increasing to 1.1.11 in package.json made it work.
